export const ORIGINALS = [
  {
    slug: "kite-line",
    title: "Kite Line",
    genre: "Reflex",
    sessionMinutes: 6,
    fantasy: "Guide a paper kite through shifting winds above a golden coastal city.",
    description:
      "Hold a line of wind and let it go. Kite Line is a short reflex session about staying inside moving corridors of air above an amber coast.",
    howToPlay: [
      "Keep the kite inside the glowing wind corridor.",
      "Hold to climb. Release to settle.",
      "Leaving the corridor reduces stability. Recover before it tears.",
    ],
    cover: "/covers/kite-line-cover.png",
    maxScore: 50000,
  },
  {
    slug: "lantern-path",
    title: "Lantern Path",
    genre: "Puzzle",
    sessionMinutes: 8,
    fantasy: "Light forgotten lanterns and trace one unbroken path through a sleeping garden.",
    description: "A quiet garden of lantern nodes. Light each one by tracing a single path that never doubles back.",
    howToPlay: [
      "Start on any lantern and move to an adjacent lantern.",
      "Visit every lantern exactly once.",
      "Complete the path to wake the garden.",
    ],
    cover: "/covers/lantern-path-cover.png",
    maxScore: 10000,
  },
  {
    slug: "tide-tap",
    title: "Tide Tap",
    genre: "Rhythm",
    sessionMinutes: 5,
    fantasy: "Follow the ocean’s rhythm as luminous waves carry melodies toward distant shores.",
    description: "Read the expanding rings and tap when a wave meets the horizon ring.",
    howToPlay: [
      "Watch the luminous ring grow toward the gold horizon.",
      "Tap or press Space as it meets the ring.",
      "Sound is optional. Timing is always visible.",
    ],
    cover: "/covers/tide-tap-cover.png",
    maxScore: 500,
  },
  {
    slug: "paper-gharial",
    title: "Paper Gharial",
    genre: "Calm",
    sessionMinutes: 7,
    fantasy: "Drift a paper gharial along a monsoon river.",
    description: "Steer a folded river creature through gentle currents.",
    howToPlay: ["Stay in the current.", "Collect floating lanterns.", "Avoid snags."],
    cover: "/covers/paper-gharial-cover.png",
    maxScore: 20000,
  },
  {
    slug: "rangoli-recall",
    title: "Rangoli Recall",
    genre: "Puzzle",
    sessionMinutes: 6,
    fantasy: "Remember a rangoli pattern and restore it from memory.",
    description: "A short memory session of colour and order.",
    howToPlay: ["Watch the pattern.", "Repeat it in order.", "Complete the floor."],
    cover: "/covers/rangoli-recall-cover.png",
    maxScore: 2000,
  },
  {
    slug: "two-player-fold",
    title: "Two-player Fold",
    genre: "Party",
    sessionMinutes: 8,
    fantasy: "Fold paper with a friend on one device.",
    description: "A cooperative folding puzzle for two.",
    howToPlay: ["Take turns placing folds.", "Match the silhouette.", "Finish the figure."],
    cover: "/covers/two-player-fold-cover.png",
    maxScore: 5000,
  },
] as const;

export const COLLECTION: Array<{
  slug: string;
  title: string;
  genre: string;
  sessionMinutes: number;
  maxScore: number;
}> = [
  { slug: "solitaire", title: "Solitaire (Klondike)", genre: "Card & Board", sessionMinutes: 15, maxScore: 10000 },
  { slug: "spider-solitaire", title: "Spider Solitaire", genre: "Card & Board", sessionMinutes: 15, maxScore: 10000 },
  { slug: "rummy", title: "Rummy", genre: "Card & Board", sessionMinutes: 15, maxScore: 5000 },
  { slug: "ludo", title: "Ludo", genre: "Card & Board", sessionMinutes: 15, maxScore: 1000 },
  { slug: "chess", title: "Chess", genre: "Card & Board", sessionMinutes: 15, maxScore: 100 },
  { slug: "carrom", title: "Carrom", genre: "Card & Board", sessionMinutes: 15, maxScore: 500 },
  { slug: "sudoku", title: "Sudoku", genre: "Puzzle", sessionMinutes: 5, maxScore: 10000 },
  { slug: "2048", title: "2048", genre: "Puzzle", sessionMinutes: 5, maxScore: 200000 },
  { slug: "crossword", title: "Crossword", genre: "Puzzle", sessionMinutes: 5, maxScore: 5000 },
  { slug: "word-guess", title: "Word Guess", genre: "Puzzle", sessionMinutes: 5, maxScore: 2000 },
  { slug: "match-3", title: "Match-3", genre: "Puzzle", sessionMinutes: 5, maxScore: 100000 },
  { slug: "jigsaw", title: "Jigsaw", genre: "Puzzle", sessionMinutes: 5, maxScore: 1000 },
  { slug: "memory-match", title: "Memory Match", genre: "Puzzle", sessionMinutes: 5, maxScore: 5000 },
  { slug: "snake-arena", title: "Snake Arena", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 50000 },
  { slug: "blob-arena", title: "Blob Arena", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 50000 },
  { slug: "endless-runner", title: "Endless Runner", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 100000 },
  { slug: "aim-trainer", title: "Aim Trainer", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 5000 },
  { slug: "tower-defense", title: "Tower Defense", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 100000 },
  { slug: "racing-rush", title: "Racing Rush", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 100000 },
  { slug: "bubble-shooter", title: "Bubble Shooter", genre: "Arcade & Skill", sessionMinutes: 5, maxScore: 100000 },
  { slug: "general-knowledge", title: "General Knowledge", genre: "Trivia & Quiz", sessionMinutes: 5, maxScore: 2000 },
  { slug: "sports-trivia", title: "Sports Trivia", genre: "Trivia & Quiz", sessionMinutes: 5, maxScore: 2000 },
  { slug: "live-trivia", title: "Live Trivia", genre: "Trivia & Quiz", sessionMinutes: 5, maxScore: 5000 },
  { slug: "movie-trivia", title: "Movie Trivia", genre: "Trivia & Quiz", sessionMinutes: 5, maxScore: 2000 },
  { slug: "idle-city", title: "Idle City", genre: "Strategy & Simulation", sessionMinutes: 5, maxScore: 100000 },
  { slug: "tycoon", title: "Tycoon / Business Simulator", genre: "Strategy & Simulation", sessionMinutes: 5, maxScore: 100000 },
  { slug: "territory-strategy", title: "Turn-Based Strategy", genre: "Strategy & Simulation", sessionMinutes: 5, maxScore: 1000 },
  { slug: "draw-guess", title: "Draw & Guess", genre: "Multiplayer Party", sessionMinutes: 5, maxScore: 5000 },
  { slug: "multiplayer-ludo", title: "Multiplayer Ludo Rooms", genre: "Multiplayer Party", sessionMinutes: 5, maxScore: 1000 },
  { slug: "trivia-battle", title: "Trivia Battle", genre: "Multiplayer Party", sessionMinutes: 5, maxScore: 5000 },
];
